# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8588925b273c003aaa3eb775d278c646940d2a5c92018b6ddf216975997af33906b657352bdeadcecb8f13f4d7f1150adc9d6b85bb6383c91926b17ece02182

test:
  secret_key_base: aab12d7d3b5f0c908c14b056c2ed7d4ebb18d23ec14425047b775055d9033a106bb6a1ee315f7510c7eaf4a42b3758f4a15db667f6569990e940aba1f2f680af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
